# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # 统一合并的所有挂载点配置
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/b346a5a5-5e8e-4cde-afa7-77e92d687e64";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/b346a5a5-5e8e-4cde-afa7-77e92d687e64";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/999A-AD7B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

    # Windows C 盘
    "/home/lk/win11/c" = {
      device = "/dev/disk/by-uuid/452F636A10A034B3";
      fsType = "ntfs3";
      options = [ "defaults" "noatime" "rw" "uid=1000" "gid=100" ];
    };

    # Windows D 盘
    "/home/lk/win11/D" = {
      device = "/dev/disk/by-uuid/45B78617C66EE19E";
      fsType = "ntfs3";
      options = [ "defaults" "noatime" "rw" "uid=1000" "gid=100" ];
    };
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
